<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-03-21 at 12:03:53.
 */
class DeviceTest extends TestCase {

    /**
     * @var Device
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Device;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Device::index
     * @todo   Implement testIndex().
     */
    public function testIndex() {
        
        $output = $this->request('GET', 'device/index');
        $this->assertContains(
            'ip', $output
        );
        
    }

    /**
     * @covers Device::view
     * @todo   Implement testView().
     */
    public function testView() {
        $output = $this->request('GET', 'device/view');
        $this->assertContains(
            'ip', $output
        );
    }

    /**
     * @covers Device::add
     * @todo   Implement testAdd().
     */
    public function testAdd() {
     $output = $this->request('GET', 'device/add/12234');
        $this->assertContains(
            'ip', $output
        );
    }

    /**
     * @covers Device::change_state
     * @todo   Implement testChange_state().
     */
    public function testChange_state() {
       $output = $this->request('GET', 'device/change_state/12234/1');
        $this->assertContains(
            'ip', $output
        );
    }

    /**
     * @covers Device::flaglist
     * @todo   Implement testFlaglist().
     */
    public function testFlaglist() {
         $output = $this->request('GET', 'device/falglist');
        $this->assertContains(
            'ip', $output
        );
    }

}
