<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-03-23 at 11:47:45.
 */
class Process_tree_modelTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Process_tree_model
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Process_tree_model;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * Generated from @assert (0, 0) == TRUE.
     *
     * @covers Process_tree_model::validate_change_state
     */
    public function testValidate_change_state() {
        $this->assertEquals(
                TRUE
                , $this->object->validate_change_state(0, 0)
        );
    }

    /**
     * Generated from @assert (2, 0) == TRUE.
     *
     * @covers Process_tree_model::validate_change_state
     */
    public function testValidate_change_state2() {
        $this->assertEquals(
                TRUE
                , $this->object->validate_change_state(2, 0)
        );
    }

    /**
     * Generated from @assert (4, 1) == TRUE.
     *
     * @covers Process_tree_model::validate_change_state
     */
    public function testValidate_change_state3() {
        $this->assertEquals(
                TRUE
                , $this->object->validate_change_state(4, 1)
        );
    }

    /**
     * Generated from @assert (0, 6) == FALSE.
     *
     * @covers Process_tree_model::validate_change_state
     */
    public function testValidate_change_state4() {
        $this->assertEquals(
                FALSE
                , $this->object->validate_change_state(0, 6)
        );
    }

    /**
     * Generated from @assert (2, 6) == FALSE.
     *
     * @covers Process_tree_model::validate_change_state
     */
    public function testValidate_change_state5() {
        $this->assertEquals(
                FALSE
                , $this->object->validate_change_state(2, 6)
        );
    }

}
